
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module lab4TF2(
	input 		          		ADC_CLK_10,
	input 		          		MAX10_CLK1_50,
	input 		          		MAX10_CLK2_50,
	output		     [7:0]		HEX0,
	output		     [7:0]		HEX1,
	output		     [7:0]		HEX2,
	output		     [7:0]		HEX3,
	output		     [7:0]		HEX4,
	output		     [7:0]		HEX5,
	input 		     [1:0]		KEY,
	output		     [9:0]		LEDR,
	input 		     [9:0]		SW
);



wire [7:0] N_wire;
wire [3:0] sqrtResult;

reg [3:0] addrcounter = 4'b0000;

always @ (negedge KEY[1] or negedge KEY[0]) begin
if (!KEY[0])
addrcounter = 4'b0000;
else
addrcounter = addrcounter + 1;
end


ram_16x4 uut0 (.clk(MAX10_CLK1_50), .addr(addrcounter), .mwr(1'b0), .mdi(8'b00000000), .mdo(N_wire));

 squareroot uut1 (.Clock(MAX10_CLK1_50), .Resetn(KEY[0]), .Start(KEY[1]), .InputVal(N_wire), .Done(LEDR[0]), .OutputSqrt(sqrtResult));
 
 hexdisplay hex0 ( .X(sqrtResult), .Y(HEX0));
 hexdisplay hex1 ( .X(N_wire[3:0]), .Y(HEX1));
 hexdisplay hex2 ( .X(N_wire[7:4]), .Y(HEX2));
 
  hexdisplay hex5 ( .X(addrcounter), .Y(HEX5));

 
 endmodule
 
 