
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module lab4(

	//////////// CLOCK //////////
	input 		          		ADC_CLK_10,
	input 		          		MAX10_CLK1_50,
	input 		          		MAX10_CLK2_50,

	//////////// SEG7 //////////
	output		     [7:0]		HEX0,
	output		     [7:0]		HEX1,
	output		     [7:0]		HEX2,
	output		     [7:0]		HEX3,
	output		     [7:0]		HEX4,
	output		     [7:0]		HEX5,
	//////////// KEY //////////
	input 		     [1:0]		KEY,
	//////////// LED //////////
	output		     [9:0]		LEDR,
	//////////// SW //////////
	input 		     [9:0]		SW
);


wire clk;
assign clk = KEY[0];

wire [3:0] addr;
assign addr = SW[7:4];

wire [3:0] mdi;
assign mdi = SW[3:0];

wire we;
assign we = SW[9];

wire selectram;
assign selectram = SW[8];

wire [3:0] mdo0, mdo1;

wire mwr0 = we & !selectram;
wire mwr1 = we & selectram;


ram_16x4 ra0 (.clk(MAX10_CLK1_50), .addr(addr), .mwr(mwr0), .mdi(mdi), .mdo(mdo0));
ram_16x4 ra1 (.clk(MAX10_CLK1_50), .addr(addr), .mwr(mwr1), .mdi(mdi), .mdo(mdo1));

hexdisplay hex0 ( .X(mdo0), .Y(HEX0));
hexdisplay hex1 ( .X(mdo1), .Y(HEX1));
hexdisplay hex2 ( .X(mdi), .Y(HEX2));
hexdisplay hex3 ( .X(addr), .Y(HEX3));







endmodule
